title: IA na Prática I
description: Projetos e ferramentas de IA aplicadas à gestão e produtividade.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Adiciona CSS personalizado
include:
  - assets/css/custom.css